version: '3'

services:
  pdal:
    image: pdal/pdal:latest
    volumes:
      - ./data:/data
  web:
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - redis
    env_file:
      - .env
  redis:
    image: "redis:alpine"
  worker:
    build: .
    command: celery -A app.celery worker --loglevel=info
    volumes:
      - .:/app
      - ./data:/data
    depends_on:
      - redis
    env_file:
      - .env
